// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPermission = `-- name: CreatePermission :exec
INSERT INTO document_permissions (user_id, document_id, role)
VALUES(
    $1,
    $2,
    $3
)
RETURNING user_id, document_id, role, created_at, updated_at
`

type CreatePermissionParams struct {
	UserID     uuid.UUID
	DocumentID uuid.UUID
	Role       string
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createPermission, arg.UserID, arg.DocumentID, arg.Role)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE from document_permissions WHERE user_id = $1 AND document_id = $2
`

type DeletePermissionParams struct {
	UserID     uuid.UUID
	DocumentID uuid.UUID
}

func (q *Queries) DeletePermission(ctx context.Context, arg DeletePermissionParams) error {
	_, err := q.db.ExecContext(ctx, deletePermission, arg.UserID, arg.DocumentID)
	return err
}

const getUsersFromDocument = `-- name: GetUsersFromDocument :many
SELECT u.email ,u.id , d.role
FROM document_permissions d
INNER JOIN users u 
ON u.id = d.user_id
WHERE document_id = $1
`

type GetUsersFromDocumentRow struct {
	Email string
	ID    uuid.UUID
	Role  string
}

func (q *Queries) GetUsersFromDocument(ctx context.Context, documentID uuid.UUID) ([]GetUsersFromDocumentRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersFromDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersFromDocumentRow
	for rows.Next() {
		var i GetUsersFromDocumentRow
		if err := rows.Scan(&i.Email, &i.ID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :exec
UPDATE document_permissions SET role = $1 WHERE user_id = $2 AND document_id = $3
`

type UpdatePermissionParams struct {
	Role       string
	UserID     uuid.UUID
	DocumentID uuid.UUID
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, updatePermission, arg.Role, arg.UserID, arg.DocumentID)
	return err
}
